# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new debug build to TestFlight"
  lane :debug do
    increment_build_number(xcodeproj: "Boolti.xcodeproj")
    build_number = get_build_number(xcodeproj: "Boolti.xcodeproj")
    build_app(
      scheme: "Boolti-Debug",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.nexters.boolti" => "Boolti-Provisioning-Appstore"
        }
      }
    )
    upload_to_testflight

    # discord(
    #   webhook_url: "YOUR_DISCORD_WEBHOOK_URL",
    #   username: "Fastlane Bot",
    #   message: "A new debug build (Build Number: #{build_number}) has been uploaded to TestFlight! 🚀"
    # )
  end
end
