name: Run test

on:
  push:
  # test를 위해 develop branch가 아닌 test branch로 설정
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Start xcode build 🛠
      run: |
        xcodebuild clean test -project Boolti/Boolti.xcodeproj -scheme Boolti -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest'
