name: Run Debug Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-debug:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Run tests with Debug scheme 🧪
        run: |
          xcodebuild clean test \
            -project Boolti/Boolti.xcodeproj \
            -scheme Boolti-Debug \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' \
            CODE_SIGNING_ALLOWED=NO
